###
POST http://localhost:5000/admin/login
Content-Type: application/json

{
    "id" : 1,
    "email" : "admin@gmail.com",
    "password" : "12345"

}

###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name" : "sabbir hossen",
    "password" : "12345",
    "email" : "sabbir1@gmail.com"

}

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "password" : "12345",
    "email" : "sabbir1@gmail.com"

}